CREATE TABLE TASSNT_MANIF_SERVC
(
 CASSNT_MANIF_SERVC    DECIMAL(4) NOT NULL,
 IASSNT_MANIF_SERVC    CHAR(100) NOT NULL,
 CSIT_REG              DECIMAL(1) NOT NULL,
 CUSUAR_INCL           CHAR(9) NOT NULL,
 HINCL_REG             TIMESTAMP NOT NULL,
 CUSUAR_MANUT          CHAR(9),
 HMANUT_REG            TIMESTAMP,
 CONSTRAINT SACLX020  PRIMARY KEY (CASSNT_MANIF_SERVC)
);
CREATE TABLE TFAML_MANIF_SERVC
(
 CFAML_MANIF_SERVC     DECIMAL(4) NOT NULL,
 IFAML_MANIF_SERVC     CHAR(50) NOT NULL,
 CSIT_REG              DECIMAL(1) NOT NULL,
 CUSUAR_INCL           CHAR(9) NOT NULL,
 HINCL_REG             TIMESTAMP NOT NULL,
 CUSUAR_MANUT          CHAR(9),
 HMANUT_REG            TIMESTAMP,
 CONSTRAINT SACLX120  PRIMARY KEY (CFAML_MANIF_SERVC)
);
CREATE TABLE TPRODT_MANIF_SERVC
(
 CPRODT_MANIF_SERVC    DECIMAL(4) NOT NULL,
 IPRODT_MANIF_SERVC    CHAR(100) NOT NULL,
 CSIT_REG              DECIMAL(1) NOT NULL,
 CUSUAR_INCL           CHAR(9) NOT NULL,
 HINCL_REG             TIMESTAMP NOT NULL,
 CUSUAR_MANUT          CHAR(9),
 HMANUT_REG            TIMESTAMP,
 CONSTRAINT SACLX480  PRIMARY KEY (CPRODT_MANIF_SERVC)
);
CREATE TABLE TTPO_MANIF_SERVC
(
 CTPO_MANIF_SERVC      DECIMAL(2) NOT NULL,
 ITPO_MANIF_SERVC      CHAR(50) NOT NULL,
 CSIT_REG              DECIMAL(1) NOT NULL,
 CUSUAR_INCL           CHAR(9) NOT NULL,
 HINCL_REG             TIMESTAMP NOT NULL,
 CUSUAR_MANUT          CHAR(9),
 HMANUT_REG            TIMESTAMP,
 CONSTRAINT SACLX630  PRIMARY KEY (CTPO_MANIF_SERVC)
);
CREATE TABLE TCATEG_MANIF_PSSOA
(
 CCATEG_MANIF          DECIMAL(4) NOT NULL,
 CTPO_MANIF_SERVC      DECIMAL(2) NOT NULL,
 CFAML_MANIF_SERVC     DECIMAL(4) NOT NULL,
 CPRODT_MANIF_SERVC    DECIMAL(4) NOT NULL,
 CASSNT_MANIF_SERVC    DECIMAL(4) NOT NULL,
 CSIT_REG              DECIMAL(1) NOT NULL,
 CUSUAR_INCL           CHAR(9) NOT NULL,
 HINCL_REG             TIMESTAMP NOT NULL,
 CUSUAR_MANUT          CHAR(9),
 HMANUT_REG            TIMESTAMP,
 CONSTRAINT SACLX060  PRIMARY KEY (CCATEG_MANIF),
 CONSTRAINT SACLX061  UNIQUE (CTPO_MANIF_SERVC, CFAML_MANIF_SERVC, CPRODT_MANIF_SERVC, CASSNT_MANIF_SERVC),
 CONSTRAINT SACL6301  FOREIGN KEY (CTPO_MANIF_SERVC)
  REFERENCES TTPO_MANIF_SERVC  (CTPO_MANIF_SERVC)
  ON DELETE RESTRICT,
 CONSTRAINT SACL1201  FOREIGN KEY (CFAML_MANIF_SERVC)
  REFERENCES TFAML_MANIF_SERVC  (CFAML_MANIF_SERVC)
  ON DELETE RESTRICT,
 CONSTRAINT SACL4801  FOREIGN KEY (CPRODT_MANIF_SERVC)
  REFERENCES TPRODT_MANIF_SERVC  (CPRODT_MANIF_SERVC)
  ON DELETE RESTRICT,
 CONSTRAINT SACL0201  FOREIGN KEY (CASSNT_MANIF_SERVC)
  REFERENCES TASSNT_MANIF_SERVC  (CASSNT_MANIF_SERVC)
  ON DELETE RESTRICT
);
